---
# code: language=ansible
- name: Create New Users
  vars_files:
    - inventory/group_vars/all
    - inventory/group_vars/development
  hosts: "{{ host_or_group }}"
  gather_facts: false
  become: true
  tasks:
    - name: Create Users Task
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        password: "{{ default_user_password | password_hash('sha512', 'A512') }}"
        shell: /bin/bash
        group: "{{ admin_group }}"
      loop: "{{ users }}"
